version: '3.8'

services:
  bot-service:
    build: .
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - bot-network

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge

volumes:
  postgres_data:
